#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99
STOP=11

PROG="/usr/sbin/neteventd.py"

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/python3 /usr/sbin/neteventd.py
    procd_set_param respawn 3600 5 0   # respawn forever, restart if it crashes
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    killall neteventd.py 2>/dev/null
}
